// <auto-generated />
namespace PharmaAssist2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedeliveryman : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedeliveryman));
        
        string IMigrationMetadata.Id
        {
            get { return "202107031450339_updatedeliveryman"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
